README.md

docs: add note about using a single configuration file

---

.github/renovate.json

chore: reconfigure renovate

---

src/entrypoint.sh

We don't need to switch to renovate work dir

feat: simplify entrypoint

---

.github/workflows/build.yml
src/docker.ts
src/renovate.ts

* mount `docker.sock` and `/tmp` to renovate
* use slim image
closes: #48

feat: use slim image

---

package.json

Fixes the release failure of https://github.com/renovatebot/github-action/runs/663943940

chore(release): fix release:version script

---

src/renovate.ts

Note that I've also changed the group regex to not search until the end of the line (removed `$`.
So now this will also match `docker:x:968:jdebruijn` for example, which is very useful when testing locally. I'll probably create a separate PR soon for adding the steps how to test locally.

fix: throw error if docker group cannot be found

---

.github/workflows/build.yml
README.md
example/renovate.json

feat(config): add support for regular Renovate config files

---

.github/renovate.json

until renovatebot/renovate#7434 is done
superseeds: #324

chore: add gh-action manager

---

README.md

This pull request add example for how to use renovate GitHub Action with a GitHub App credentials instead of a personal access tokens (PAT) that are tied to a single user.
Close #500

docs: add example for use with GitHub App

---

.github/renovate.json

* https://github.com/suzuki-shunsuke/test-renovate-3/pull/10
* https://github.com/suzuki-shunsuke/test-renovate-3/blob/d9d0683ae00816103b2685f73ca7320213e28bad/.github/renovate.json

chore: update GitHub Actions in README by Renovate

---

.github/workflows/build.yml
example/renovate-config.js
example/renovate.json
package-lock.json

This way the e2e tests are also working for fork pr's

test: use github token for e2e

---

README.md

* docs: fix broken links
* ~docs: update GitHub Actions https://github.com/renovatebot/github-action/releases~
* https://github.com/renovatebot/github-action/pull/556#discussion_r693727790

docs: fix broken links and update GitHub Actions

---

.github/workflows/build.yml

* Skip local pr builds
* auto cancel outdated builds

ci: update workflow

---

src/renovate.ts

fix: use numeric docker user

---

example/renovate-config.js
example/renovate.json

When running renovate with the example config provided, it says that the configuration needs to be migrated. Here is a PR that updates you example config.

test: migreate examples

---

.github/workflows/build.yml
action.yml
package.json

Migrate to node v16
- closes #607 
- closes #610

feat: migrate to node v16

---

README.md

Added an explanation on how to use environment variables with an example of using a host rule.
This is related to the issue https://github.com/renovatebot/github-action/issues/585

docs: Clarify the README

---

example/renovate-config.js

test: duplicate key

---

.github/renovate.json
src/docker.ts
src/get-version.ts

fix: broken release

---

README.md

Fixes renovatebot/github-action#690

docs: update github app token vending to non-archived action

---

README.md
action.yml
src/input.ts

- Closes https://github.com/renovatebot/github-action/issues/585

feat: allow override env regex

---

.github/workflows/build.yml
.releaserc.json
README.md
action.yml
package.json
src/docker.ts
src/get-version.ts
src/input.ts
yarn.lock

BREAKING CHANGE: Action does no longer follow Renovate versions.
Use `renovate-version` option to pin to a specific version.

feat!: use semantic release

---

example/renovate-config.js

- Run Prettier on all files
It only fixed this one file. 😄

chore: run Prettier on all files

---

src/renovate.ts

- fixes #713
- fixes #736 
- reopens #646
BREAKING CHANGE: The action now uses the default docker user again.

feat!: use default docker user

---

action.yml

docs: fix wrong image name in action description

---

CHANGELOG.md

- Fix broken link
- Rewrite link sentence a bit
Fixing a broken link.

chore: update link to changelog on release branch

---

README.md

While the link goes to the "classic" tokens, make it more explicit.
Closes: #777

docs: mention that Fine-grained PATs are not supported

---

README.md

Also https://github.com/renovatebot/renovate/pull/27101

docs(github): change GitHub App token Action suggested to GitHub official

---

README.md

https://github.com/renovatebot/github-action/issues/872 
https://github.com/renovatebot/renovate/releases/tag/39.0.0

docs: Fix permissions for Renovate 39

---

.github/renovate.json
README.md
action.yml
src/docker.ts
src/index.ts
src/input.ts
src/renovate.ts

Allows better tree shaking while bundling.
Also prepared for renovate major version pinning.

fix(refactor): use named imports
