- .versionrc.js
Just noted in the v19.236.1 release that the dist folder was not added to the releases branch.
> chore(release): include dist folder in release commit

- .github/renovate.json
allow automerge all renovate versions
> chore(renovate): don't require approval

- .github/renovate.json
Otherwise automerge can be deferred to long after approval
> chore: allow lockfile maintenance at any time

- .github/workflows/build.yml
no longer needed and does nothing than issue an error bug continues successfully
> chore: remove obsolete cleanup job

- package-lock.json
- package.json
> fix(deps): replace `@zeit/ncc`, which is deprecated, with `@vercel/ncc`

- .github/workflows/build.yml
- README.md
- action.yml
- example/renovate-config.js
- example/renovate.json
- src/index.ts
- src/input.ts
- src/renovate.ts
Inputs may now be provided using environment variables, as well as the existing inputs. None of the
inputs are required any more, so it is possible to use only environment variables. Nevertheless all
inputs must be provided in some way, either using the input or their corresponding environment
variables.
BREAKING CHANGE: The `configurationFile` input no longer has a default value.
Closes #136.
> feat: add passing of Renovate environment variables

- .github/workflows/build.yml
We can ignore commit lint, as we do squash merge
> ci: allow failing commitlint

- README.md
This URL does not exist anymore: https://docs.renovatebot.com/self-hosting/
> docs: Remove reference to 404 page

- src/input.ts
Renovate is failing in a large repository with the error
```
<--- Last few GCs --->
[9:0x53f4b00]  1875576 ms: Scavenge 1781.0 (1983.4) -> 1779.1 (1999.4) MB, 82.3 / 0.0 ms  (average mu = 0.795, current mu = 0.725) allocation failure 
[9:0x53f4b00]  1875776 ms: Scavenge 1795.0 (1999.4) -> 1795.1 (1999.4) MB, 84.2 / 0.0 ms  (average mu = 0.795, current mu = 0.725) allocation failure 
[9:0x53f4b00]  1875869 ms: Scavenge 1795.1 (1999.4) -> 1793.1 (2015.4) MB, 93.1 / 0.0 ms  (average mu = 0.795, current mu = 0.725) allocation failure 
<--- JS stacktrace --->
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
1: 0xa3aaf0 node::Abort() [node]
2: 0x970199 node::FatalError(char const*, char const*) [node]
3: 0xbba45e …
```
> fix: Allow passing through NODE_OPTIONS

- README.md
Adds to README.md to clarify why `GITHUB_TOKEN` cannot be used to drive the bot.  
Closes #633
> docs: clarify why bot cannot use `GITHUB_TOKEN`

- README.md
The command to base64 encode a .pem file doesn't work (reasons described in the linked issue). I've adjusted the instructions, and removed the superflous `&& echo` command.
Fixes https://github.com/renovatebot/github-action/issues/652
> Adjust documentation for macOS

- README.md
Updates the GitHub App example documentation to point to the published Renovate GitHub App documentation.
Closes #653
> Link the readme to the Renovate GitHub App documentation

- .github/workflows/build.yml
Resolve #697 
Update `.github/workflows/build.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
**AS-IS**
```yml
echo "::set-output name=changelog::${changelog}"
```
**TO-BE**
```yml
echo "changelog=${changelog}" >> $GITHUB_OUTPUT
```
> ci: replace deprecated command with env file

- src/renovate.ts
BREAKING CHANGE: binary-source is now `install` and the container runs with host user id.
> feat!: remove docker socket and change to current user

- .github/renovate.json
- Fix typos in Renovate configuration
Drive-by PR to fix some typos. 😄
> chore: fix typos in Renovate configuration

- README.md
> docs: fix typo in readme "table of contents"

- src/docker.ts
`latest` tag now points to the `slim` image.
> fix: use full image again by default

- .github/renovate.json
- README.md
- action.yml
- src/docker.ts
- src/input.ts
- Drop `useSlim`, `latest` docker tag is now the slim image.
- Update readme for full image usage
- Use latest image by default
- closes #755
**Please add this to the commit body**
```
BREAKING CHANGE: The action now uses the slim renovate version by default.
> feat!: drop `useSlim` and use `latest` tag

- .github/workflows/build.yml
- action.yml
- package.json
Node v16 is deprecated on GitHub Runners. Node v20 should be used instead.
> feat!: migrate to node v20

- README.md
I recently introduced quite an advanced (if I say so myself) configuration for the official Jenkins Helm Chart using this GitHub Action. It took me quite a lot of trial and error to get everything working, so it might be nice to refer people there looking for a similar configuration. Also, the link to the vidavidorra example didn't work anymore. It also looks like it has been quite simplified, so I'm not sure if it still counts as an advanced configuration.
> docs: Add another advanced configuration example

- README.md
- action.yml
- src/input.ts
- src/renovate.ts
Closes #852 
Related to:
- https://github.com/renovatebot/renovate/discussions/29822#discussioncomment-9864079
> feat: Add `docker-network` input param

- example/renovate-config.js
- example/renovate-config.json
change includeForks to forkProcessing and stabilityDays to minimumReleaseAge in example global configs.
stabilityDays -> minimumReleaseAge changed by https://github.com/renovatebot/renovate/pull/21376
includeForks -> forkProcessing changed by https://github.com/renovatebot/renovate/pull/20759
> chore: update example files with newer options

- example/renovate-config.js
Renovate would throw validation error if this property not a string
```
Error type: The renovate configuration file contains some invalid settings
Message: Configuration option packageRules[2].minimumReleaseAge should be a string
```
> chore: fix renovate example

- README.md
according [requireConfig](https://docs.renovatebot.com/self-hosted-configuration/#requireconfig) docs, requireConfig now accept `required`, `optional`, `ignored` not boolean.
> docs(readme): requireConfig now accept required, optional, ignored not boolean.

- README.md
The doc explains step by step what to do, but misses the step of, once the Github app is created, install it in the needed account.
> docs: add github app account install step
